name = "My Fabulously Optimized"
author = "rikzy75"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f5ab7923adf2b754a8c378d14a9221b20512aaf221d1384d8ee5b90ddaca5c9d"

[versions]
fabric = "0.19.2"
minecraft = "26.1.2"

[options]
acceptable-game-versions = []
