name = "My Fabulously Optimized"
author = "rikzy75"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a0909d11cbff5d6abc81c224474f85b7a77e08bd0ce2592ab030f62e5df0d9cf"

[versions]
fabric = "0.19.2"
minecraft = "26.1.2"

[options]
acceptable-game-versions = []
