name = "My Fabulously Optimized"
author = "rikzy75"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ad5a154951aed77fe811b4738a96948a1805310bddd90b762e2d2a3764fc2d60"

[versions]
fabric = "0.19.2"
minecraft = "26.1.2"

[options]
acceptable-game-versions = []
